### ISSUE TITLE
Error: IllegalArgument: width is not integer

### ISSUE THREAD

**Issue by alecf** [applitools/eyes.webdriverio.javascript#38]
I'm getting a crash using `checkRegionBy` with the 2.0.0 version of eyes.webdriverio. Downgrading to 1.2.1 fixes it.

The problem seems to be in `@applitools/eyes.webdriverio/src/wrappers/EyesWebElement.js`, where it extracts the return result:

```
  getClientWidth() {
    return this.executeScript(JS_GET_CLIENT_WIDTH).then(r => {
      const {value} = r;
      return Math.ceil(parseFloat(value));
    });
  }
```

When I inspected, `r` is the actual return value (in my case, 1280) but the code seems to think the return result is `{ value: 1280 }` - so when `const { value } = 1280;` puts `undefined` in value, and then it is parsed, it becomes `NaN`.

I wasn't sure if the `{ value: ..}` thing was the new way or the old way, so I don't have a patch to fix this.

The stack:

```
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] Map Export Tests
[chrome #0-0]   1) should open map export
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 failing (36s)
[chrome #0-0]
[chrome #0-0] 1) Map Export Tests should open map export:
[chrome #0-0] IllegalArgument: width is not integer: 'NaN'
[chrome #0-0] Error: IllegalArgument: width is not integer: 'NaN'
[chrome #0-0]     at Function.isInteger (/Users/alecf/uf/frontend/node_modules/@applitools/eyes.sdk.core/lib/ArgumentGuard.js:137:13)
[chrome #0-0]     at Function.greaterThanOrEqualToZero (/Users/alecf/uf/frontend/node_modules/@applitools/eyes.sdk.core/lib/ArgumentGuard.js:85:21)
[chrome #0-0]     at new RectangleSize (/Users/alecf/uf/frontend/node_modules/@applitools/eyes.sdk.core/lib/geometry/RectangleSize.js:37:19)
[chrome #0-0]     at Object.eyesElement.getClientHeight.then.elementHeight (/Users/alecf/uf/frontend/node_modules/@applitools/eyes.webdriverio/src/Eyes.js:422:27)
[chrome #0-0]     at Object.exec (/Users/alecf/uf/frontend/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
[chrome #0-0]     at Object.resolve (/Users/alecf/uf/frontend/node_modules/webdriverio/build/lib/webdriverio.js:191:29)
[chrome #0-0]     at /Users/alecf/uf/frontend/node_modules/webdriverio/build/lib/webdriverio.js:540:32
[chrome #0-0]     at _fulfilled (/Users/alecf/uf/frontend/node_modules/q/q.js:854:54)
[chrome #0-0]     at /Users/alecf/uf/frontend/node_modules/q/q.js:883:30
[chrome #0-0]     at Promise.promise.promiseDispatch (/Users/alecf/uf/frontend/node_modules/q/q.js:816:13)
[chrome #0-0]
```

**Comment by yuriieasternpeak** [comment]
Fixed in version 2.0.1

**Comment by jtappi** [comment]
I am using https://www.npmjs.com/package/@applitools/eyes.webdriverio 2.10.0 and am still having issues, particular to Firefox.  Chrome and Safari do not throw this error.

Error: IllegalArgument: width is not integer
    at Function.isInteger (/Users/userName/folder/projectName/node_modules/@applitools/eyes-common/lib/utils/ArgumentGuard.js:141:13)
    at Function.greaterThanOrEqualToZero (/Users/userName/folder/projectName/node_modules/@applitools/eyes-common/lib/utils/ArgumentGuard.js:87:21)
    at new RectangleSize (/Users/userName/folder/projectName/node_modules/@applitools/eyes-common/lib/geometry/RectangleSize.js:39:19)
    at new RectangleSize (/Users/userName/folder/projectName/node_modules/@applitools/eyes-common/lib/geometry/RectangleSize.js:31:14)
    at EyesWebElement.getSize (/Users/userName/folder/projectName/node_modules/@applitools/eyes.webdriverio/src/wrappers/EyesWebElement.js:359:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

***I tried using 2.0.1 but the same error is thrown

**Comment by yuriieasternpeak** [comment]
> I am using https://www.npmjs.com/package/@applitools/eyes.webdriverio 2.10.0 and am still having issues, particular to Firefox. Chrome and Safari do not throw this error.
> 
> Error: IllegalArgument: width is not integer
> at Function.isInteger (/Users/userName/folder/projectName/node_modules/@applitools/eyes-common/lib/utils/ArgumentGuard.js:141:13)
> at Function.greaterThanOrEqualToZero (/Users/userName/folder/projectName/node_modules/@applitools/eyes-common/lib/utils/ArgumentGuard.js:87:21)
> at new RectangleSize (/Users/userName/folder/projectName/node_modules/@applitools/eyes-common/lib/geometry/RectangleSize.js:39:19)
> at new RectangleSize (/Users/userName/folder/projectName/node_modules/@applitools/eyes-common/lib/geometry/RectangleSize.js:31:14)
> at EyesWebElement.getSize (/Users/userName/folder/projectName/node_modules/@applitools/eyes.webdriverio/src/wrappers/EyesWebElement.js:359:12)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> 
> ***I tried using 2.0.1 but the same error is thrown

can you reproduce the bug on latest (2.10.2) version?
